### ISSUE TITLE
Display instructions after exiting the bakery

### ISSUE THREAD

**Issue by allindow** [nskins/goby#14]
When I first encounter Bob's bakery and type exit, it just gives a new line.
It would be helpful to display the available commands at that point. My inclination was to type "exit" again which wasn't a valid command.

Welcome to Bob's Bakery.
Current gold in your pouch: 0.
Would you like to buy, sell, or exit?: exit

> exit

That isn't an available command at this time.
Type 'help' for a list of available commands.

**Comment by nskins** [comment]
Hi Angela, thanks for reporting this. There are two issues with this potential solution:

1. Since the shop knows nothing about the tile upon which it sits, it cannot report the available commands from other events on the tile.
2. Given the above point, we would need to print the commands after _every_ user command, which would be too verbose for simple commands like 'use,' 'inv,' etc.

I think a good solution to this issue would be a simple line of text that informs the player about leaving the shop. A possible solution could be "Player1 leaves Bob's Bakery." Hopefully this better conveys the player has now returned to the "map."

**Comment by allindow** [comment]
@nskins I like that solution and think that would make sense to have that confirmation that you've successfully exited

**Comment by silvestrijonathan** [comment]
@nskins I came across this issue and would be happy to submit a PR with that line of text added.
