### ISSUE TITLE
Remove the type variable from Equippable

### ISSUE THREAD

**Issue by nskins** [nskins/goby#36]
When one needs to hash the type in the Entity's 'outfit' variable, we can just use the type of the Equippable (Weapon, Helmet, etc.) as the KEY of the hash. Then we won't need to store extra data for a type variable.

http://stackoverflow.com/questions/15769739/determining-type-of-an-object-in-ruby

**Comment by scosbet** [comment]
Hey there, I've just been looking at this and it seems like the implementation of the behaviour in the 'Ayara' example is slightly different from how this issue and the examples in the spec files implies it should work.

In the 'Ayara' example the type of the Equippable is subclassed (e.g `KarateBottom < Legs`) so making this change to use the type as the key in the outfit hash would allow the player to equip multiple Eqiuppables with the same parent.

Looking at the specs however it seems like the intention was to have the name of the Equippable stored in the 'name' property as opposed to creating a subclass 

e.g entity_spec:221 `Weapon.new(name: "Hammer",
                                                   stat_change: { attack: 3,
                                                                  defense: 2,
                                                                  agility: 4 },
                                                   attack: Attack.new(name: "Bash")), 1)`

Is my interpretation accurate? Is the 'Ayara' example incorrect or is implementing this change just a bit more complex than it first appeared?

**Comment by nskins** [comment]
Hi @scosbet. Yes, you're correct. My original description is out-of-date... sorry about that. I tried implementing it recently and noticed exactly what you've described. I'd prefer that we could create objects in the method given in the 'Ayara' example as well as the spec example. Or perhaps there is a better way to store implementations of these abstract classes without explicitly creating a subclass..? Do you have any idea?

**Comment by scosbet** [comment]
I can't think of a better way than it's currently implemented if you want to have the option of using either method. The only way to retain that and still be able to remove the '@type' from the Equippable sub-classes would be to embed knowledge of the different types inside the Entity class which I don't think would be an improvement.

One enhancement suggestion would be to turn the Equippable class in to a module though. I think this is more of a behaviour of an Item rather than a specialisation of an Item so a module would be more appropriate. I will prepare something for you to take a look at and see what you think.

**Comment by nskins** [comment]
Some progress has been made by #90, and it is currently unknown if the original issue can be resolved.
