### ISSUE TITLE
Abstract battle() method

### ISSUE THREAD

**Issue by nskins** [nskins/goby#42]
It would be better to abstract the batte(Monster) method in the Player class into the Entity class. That way, Player can face Player and Monster can face Monster.

Additionally, there's some repeated code in this method so we can try cleaning it up.

**Comment by chrabyrd** [comment]
I'd be happy to take a stab (heh) at this.

**Comment by nskins** [comment]
What this issue really boils down to is that `Player` and `Monster` must use Liskov substitution in their inheritance of Entity. Then the `#battle(Entity)` method can be called in any of those combinations. 

We can achieve substitutability by "forcing" (I don't know Ruby's capabilities... something like abstract classes in C++?) the subtype (`Player` or `Monster`) to inherit certain "behaviors:" how to choose an attack, how to use an item, what happens on death, etc. These are "pure virtual functions" of Entity. In addition, the two subclasses should have no variables referenced in the `#battle` method that are not shared by both implementations.

**Comment by nskins** [comment]
This will also help us to implement #98!

**Comment by scosbet** [comment]
I started working on this a while ago then stopped when somebody else picked it up but I'd be happy to take a look at it again.

The solution I was working on was to create a 'Fightable' module which any Entity could implement and therefore inherit the behaviour of things that were eligible to enter in to a fight...which I think is very similar to the functionality you've described.

It was coming along quite nicely but I also remember finding the test coverage in the area limited so couldn't be certain I wasn't breaking anything.

I think in order to proceed with this we'll need to uplift the tests first/simultaneously so it's quite a sizeable task. 

I'll start chipping away at it!

**Comment by nskins** [comment]
Yes, this is very helpful. Thank you!
