### ISSUE TITLE
Optional "mini-map" visible during movement

### ISSUE THREAD

**Issue by gintavang** [nskins/goby#74]
Navigating through the map is currently difficult to do effectively without typing the 'map' command many times (if the distance to be traveled is more than a few tiles). Having the option to see a mini-map (3x3, 4x4, 5x5...) during movement will eliminate the need to go back to the map so many times.

This should also probably be an optional feature that the user can turn on and off using a default command.

**Comment by nskins** [comment]
Just realized that the 'mini-map' and the actual map won't ever actually overlap, like I mentioned previously. This is because the 'mini-map' will only show after movement (whether successful or failed) and the actual map will only show after the 'map' command.

Also make it easy to switch 3x3, 5x5, etc. via a change of one variable (in code, not user). Choose whatever default you think is best.

Suggestion: Maybe the new 'seen' tiles (from `Player.update_map`) should be the same ones that are shown on the mini-map.

**Comment by nskins** [comment]
Fixed in #76.
